spring:
  application:
    name: server

  config:
    import: classpath:security.yaml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        jdbc:
          time_zone: Asia/Seoul

  sql:
    init:
      mode: never

  web:
    resources:
      add-mappings: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

cors:
  allowed-origins: http://localhost:3000,http://localhost:8080

logging:
  level:
    com.server: debug
    org.hibernate.SQL: info