spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hanacare-test.c7skmkwg270b.ap-northeast-2.rds.amazonaws.com:3306/hanacare-test?serverTimezone=Asia/Seoul
    username: admin
    password: hanaro1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always

cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: ap-northeast-2
    s3:
      endpoint: http://localhost:4566
      bucket:
        public: hanaro-public
        private: hanaro-private

voice:
  upload-dir: src/main/resources/static/voice
  base-url: http://localhost:8080/voice/
  voice-storage-path: file:src/main/resources/static/voice/
