name: Java Spring CI with Gradle

on:
  push:
    branches: [ release/spring ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 1. 우리 서비스용 보안 설정 파일 생성 (hanacare 설정 반영)
      - name: set props
        working-directory: server
        run: |
          echo "${{ secrets.SECURITY_YAML }}" > ./src/main/resources/security.yaml

      # 2. gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        working-directory: server
        run: chmod +x gradlew

      # 3. 빌드 실행 (자코코 및 테스트 제외하여 속도 향상)
      - name: Build with Gradle
        working-directory: server
        run: ./gradlew build -x test -x jacocoTestCoverageVerification

      # 4. EC2 접속을 위한 SSH 설정
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.WAS }} >> ~/.ssh/known_hosts

      # 5. 빌드된 결과물 전송 (hanacare 전용 경로 반영)
      - name: scp jar and config to was
        run: |
          scp server/src/main/resources/security.yaml ec2-user@${{ secrets.WAS }}:/home/ec2-user/workspace/hanacare/security.yaml
          
          scp server/build/libs/*.jar ec2-user@${{ secrets.WAS }}:/home/ec2-user/workspace/hanacare/app.jar
